name: ${project.name}
main: com.github.pocketkid2.fill.FillPlugin
version: ${project.version}
author: Pocketkid2
description: Fill container blocks quickly!
commands:
    fill:
        description: Set, give, or remove a fill wand
        usage: /fill <id> <qty> <data>
        permission: fill.command
permissions:
    fill.command:
        description: Allows you to use the command /fill
        default: op
    fill.use:
        description: Allows you to use the fill wand
        default: op