  
name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout iFill
      uses: actions/checkout@v3
      with:
        path: iFill
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    
    # Build Ultimate-FactionsChat
    - name: Build iFill
      run: mvn -B package -T 1C --file iFill/pom.xml

    - name: Stage jar
      run: mkdir staging && cp iFill/target/iFill.jar staging
    - name: Rename jar
      run: mv staging/iFill*.jar staging/iFill_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: iFill_Dev-Build
        path: staging/iFill_*.jar
